### PR TITLE
Playlist Page 

### PR DESCRIPTION
**Pull request by chanchal-panpaliya**
Playlist Page 

remaining -> index.js file (for all import files).

Screens are -> 
palylist3
palylist4
palylist5

### CODE REVIEW

**Review by shrushti2000 — APPROVED** [review]
Everything looks good. Can be merged.

**Review by prathmeshjagtap — APPROVED** [review]
Code is well structured and Clean

**Review by darshandamre — APPROVED** [review]
one suggestion is use one type of naming convention across all components. for a component you were using `snake_case` and other components use different naming style.

**Review by krgarima — APPROVED** [review]
Looks good

**Pull request merged**
